[build]
  functions = "netlify/functions"
  publish = "studyhub-interactives/public"
  command = "chmod +x build.sh && ./build.sh"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["google-generativeai"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"

