[build]
  command = "bash build.sh"
  publish = "public"

[functions]
  directory = "mindmap-ai"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
