[build]
  publish = "studyhub-interactives/public"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/flashcard/*"
  to = "/flashcard/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/mindmap/mindmap-ai/*"
  to = "/mindmap/mindmap-ai/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/mindmap/mindmap-manual/*"
  to = "/mindmap/mindmap-manual/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/pdf-chat/*"
  to = "/pdf-chat/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
